# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/brunch
image: node:latest

pages:
  script:
    - echo hi
  artifacts:
    paths:
    - public
  only:
  - master
