dist: xenial

addons:
  snaps:
  - name: hugo 
    channel: extended

script:
  - hugo

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: ttp.sh
  keep-history: true
  on:
    branch: master