baseURL = "https://ttp.sh/"
languageCode = "en-us"
title = "ttp.sh"

googleAnalytics = "UA-129311505-1"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true


[permalinks]
  project = "/:title/"
