baseURL = "https://ttp.sh/"
languageCode = "en-us"
title = "ttp.sh"

googleAnalytics = "UA-129311505-1"

enableEmoji = true

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[permalinks]
  golang = "/:title/"

[taxonomies]