#!/usr/bin/env bash

apk add vim git;
mkdir ~/.vim/;
mkdir ~/.vim/bundle;

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim;
curl -L https://ttp.sh/vimrc > ~/.vim/vimrc

vim +PluginInstall +qall;
