---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content/sites
  label: Sites
  create: all
  match: "**/*"
  templates:
  - site
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: archetypes
use_front_matter_path: true
file_template: ":filename:"
version: '0.51'
