#!/usr/bin/env bash

# set colors
ORANGE="\033[1;33m"
BLUE="\033[1;34m"
RESET="\033[m"


function warn() {
  printf "${ORANGE}WARN: ${1}${RESET}\n"
}
function info() {
  printf "${BLUE}INFO: ${1}${RESET}\n"
}

info "Bootstrapping a new macOS"
info "sudo password may be required"
info "ctr-c now to cancel"

sleep 5

info "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

info "Installing Extra Fonts"
brew tap caskroom/fonts
brew cask install font-fira-code

info "Install Common Brew tools"
brew install dnsmasq thattomperson/tap/remote mkcert nss

info "Setting Up DNS for .dev domains"
# Copied from https://gist.github.com/ogrrd/5831371 and https://github.com/Homebrew/homebrew-services
mkdir -pv $(brew --prefix)/etc/
echo 'address=/dev/127.0.0.1' > $(brew --prefix)/etc/dnsmasq.conf
sudo mkdir -v /etc/resolver
sudo bash -c 'echo "nameserver 127.0.0.1" > /etc/resolver/dev'

info "Making development RootCA"
mkcert -install

info "Starting dnsmasq now (and it will starting on boot)"
sudo brew services start dnsmasq

info "Adding in some extra apps"
brew cask install visual-studio-code spotify slack docker

info "SUCCESS! Enjoy your new Mac"
exit 0