#!/usr/bin/env bash

# set colors
ORANGE="\033[1;33m"
BLUE="\033[1;34m"
RESET="\033[m"


function warn() {
  printf "${ORANGE}WARN: ${1}${RESET}\n"
}
function info() {
  printf "${BLUE}INFO: ${1}${RESET}\n"
}

info "Bootstrapping a new macOS"
info "sudo password may be required"
info "ctr-c now to cancel"

sleep 5

info "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

info "Installing mas "
brew install mas

info "Installing Extra Fonts"
brew tap caskroom/fonts
brew cask install font-fira-code

info "Installing CA Cert tools"
brew install mkcert nss

info "Installing DPS Dev-Tools"
brew Installing thattomperson/tap/remote

info "Making development RootCA"
mkcert -install

info "Adding in some extra apps"
brew cask install visual-studio-code spotify slack docker firefox

info "Downloading app from the Mac App Store"


curl https://ttp.sh/dnsmasq | sh

info "SUCCESS! Enjoy your new Mac"
exit 0