#!/usr/bin/env bash

# set colors
ORANGE="\033[1;33m"
BLUE="\033[1;34m"
RESET="\033[m"


function warn() {
  printf "${ORANGE}WARN: ${1}${RESET}\n"
}
function info() {
  printf "${BLUE}INFO: ${1}${RESET}\n"
}

info "Installing DNSMasq"

brew install dnsmasq

info "Setting Up DNS for .dev domains"

# Copied from https://gist.github.com/ogrrd/5831371 and https://github.com/Homebrew/homebrew-services
mkdir -pv $(brew --prefix)/etc/
echo 'address=/dev/127.0.0.1' > $(brew --prefix)/etc/dnsmasq.conf
sudo mkdir -v /etc/resolver
sudo bash -c 'echo "nameserver 127.0.0.1" > /etc/resolver/dev'

info "Starting dnsmasq now (and it will starting on boot)"

sudo brew services start dnsmasq